version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustruct
    - funlen
    - gocognit
    - gocyclo
    - godot
    - gomodguard
    - interfacebloat
    - lll
    - maintidx
    - mnd
    - nestif
    - nlreturn
    - noinlineerr
    - sqlclosecheck
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    asasalint:
      use-builtin-exclusions: true
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - generic
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gochecknoglobals
          - gosec
          - revive
        path: _test\.go
      - linters:
          - asasalint
          - goconst
        path: (.+)_test\.go
    paths:
      - testdata
      - bin
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - testdata
      - bin
      - third_party$
      - builtin$
      - examples$
